stages:
  - Build
  - Deploy

Build:
  stage: Build
  image: docker:latest
  before_script:
    - cd /volume1/docker/Commute-Front
    - git pull origin master
  script:
    - docker build --tag commute/front .

Deploy:
  stage: Deploy
  image: docker:latest
  before_script:
    - cd /volume1/docker/Commute-Front
  script:
    - docker stop Commute-Front
    - docker rm Commute-Front
    - docker run -d --name=Commute-Front --restart=always -p 19932:3000 commute/front:latest
